### ISSUE TITLE
Bad order in toString()

### ISSUE THREAD

**Issue by manolodd** [bolerio/mjson#10]
Hi,

I'm trying to convert JSON from/to String as follows:

        String myJSONString = "{\"user\":\"myuser\",\"pw\":\"mypass\",\"log\":true}";
        System.out.println(myJSONString);
        Json json = Json.read(myJSONString);
        System.out.println(json.toString());

That is, I expect that myJSONString.equals(json.toString()) returns true, but it does not.

The values that System.out.println() show are:

{"user":"myuser","pw":"mypass","log":true}
{"log":true,"pw":"mypass","user":"myuser"}

For myJSONString and json.toString(), respectively. Therefore, json.toString() inverts the string. Is this a bug? I want to load/store the same JSON string from/to disk several times but due to this behaviour I'm not able to do that.

PS: The problem is that next time I load the MyJSONString from this it cannot be validated using the JSON schema.

**Comment by bolerio** [comment]
The implementation uses a Java HashMap underneath and the toString implementation will simply order it the way the HashMap.iterator() does, which is not guaranteed to be the same. In fact often it is not the same and people use a LinkedHashMap which links the elements in a predictable order for iteration. But in this case the overhead is not justified. JSON.toString is for display purposes, otherwise the Json objects themselves should be compared.

**Comment by manolodd** [comment]
OK. Thank you so much.
