### ISSUE TITLE
Why json.at() returns null instead of an object?

### ISSUE THREAD

**Issue by leolux** [bolerio/mjson#20]
The following code produces a NullPointerException:

    Json json = Json.object();
    String value = json.at("notAvailable").asString();

What is the advantage of json.at("...") returning null instead of a json object? I would have expected the java null value from the _asString()_ method.

The method Json.read() for example will never return the actual Java null. Could this also be done for the method json.at("...")?

**Comment by bolerio** [comment]
I need to setup of a discussion forum/mailing list for question like this :) I looked at the Discuss project here on Github and it looks really nice, but requires a Docker instance to be placed on a cloud somewhere, heavy stuff...

Anyway, json.at(name) will return a Java null instead of a Json.nil() for a missing property because one must be able to differentiate between the two. If json.at("notAvailable") returned a Json.nil(), it would mean the property is there with a value null. json.at() will return Java null if and only if json.has() return false for the same name. Default values were introduced for cases like this:

json.at("notAvailable", "").asString() // will return empty string
json.at("notAvailable", null).asString() // will throw an UnsupportedOperationException because a null cannot be treated as a string in JSON.

**Comment by leolux** [comment]
Ok, the default value parameter solves my problem.
But how to benefit from the distinction between a non existing property and a existing property with the value null. I think that this distinction is only required in special cases and for those cases the method json.has() could still be used to achive the same. 

What do you think? If this would be made configurable would it bloat the library out of proportion?

**Comment by bolerio** [comment]
The way I see it, if you look at those two JSONs:

{  "a":5, b:null }

and

{ "a":5}

they are different. Whether that difference makes sense for certain applications and how is kind of irrelevant if the library is to be general purpose and support those two cases as being different. In JSON "null" is part of the specification, so it is represented as a particular JSON type. I think a global configuration of this sort would confuse things. That say, I always have the option of rolling your own Object type implementation via Json.Factory :)

**Comment by leolux** [comment]
Why not introducing a new internal Type for representing non existing property? The NullJson currently represents a JSON null value. But a non existing property does not need to be representet by Java null. It may be represented by NotExistingJson because the method Json.at() returns a Json which is still outside the world of java.

**Comment by bolerio** [comment]
Json is a Java library, and in Java null represents a non-existing value.
